apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres2
  name: postgres2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres2
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: be-private-data-db
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USERNAME
          value: postgres
        image: kristijonas/task1:postgres
        name: postgres2
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
