apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: sendgrpc
  name: sendgrpc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sendgrpc
    spec:
      containers:
      - image: dbarzdys/sendgrpc
        name: sendgrpc
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /etc/sendgrpc
          name: sendgrpc
      restartPolicy: Always
      volumes:
      - name: sendgrpc
        hostPath:
          path: /hosthome/kristijonas/testing/mount/
status: {}
